### ISSUE TITLE
[Good First Issues]: Review Elasticsearch Sink

### ISSUE THREAD

**Issue by Michaelg22** [vanus-labs/vanus-connect#208]
# Documentation Review

## Motivation

The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

## Details

Review and test connectors documentation

### When you test:
- Use the [playground](play.linkall.com) to test GitHub Source
- Run the connector according to the documentation
- Test every link in the documentation

### When you review the documentation:
- Grammar check
- Wrong capitalization
- All image are working
- You can understand every step.

If you have any questions or comments, please feel free to leave a comment in this issue.

## How to change it:

Comment to Claim this issue.
1. Fork the docs repository.
2. Create a branch Review GitHub Source .
3. Review document [Elasticsearch Sink](https://github.com/linkall-labs/vanus-connect/tree/main/connectors/sink-elasticsearch/README.md)
5. Change: Use the playground terminal to test the connector, Review document. 
6. Make a PR.

**Comment by singhjeetparam** [comment]
I'll take ownership of this issue. Thanks for bringing it to our attention. I'll keep you posted on my progress.
