### ISSUE TITLE
🎯 New Sink Connector Request: Google Sheets 

### ISSUE THREAD

**Issue by JieDing** [vanus-labs/vanus-connect#233]
# Sink Connector-Google Sheets

## What is a Vanus Connector

Vanus Connect allows you to skip the complex integration with external services by offering out-of-the-box connectors. Each connector acts as a proxy between outside services and your system, enabling users to have faster integrations with no codes. All data produced or processed by our connectors conforms to the [**CloudEvents specification**](https://github.com/cloudevents/spec), which helps enterprises leverage event-driven architecture to do business in the age of events.

## What is a Sink Connector

A sink connector receives CloudEvents and does some specific business logics. For example:
- MySQL Sink extracts useful data from CloudEvents and writes them to a MySQL database.
- Display Sink prints incoming CloudEvents out.
- Slack Sink extracts data from CloudEvents and send them to a Slack channel.

## Features of this Connector

- Sink-Google-Sheets allows users to insert a new row based on the incoming CloudEvents.

## How to create a new connector

1. Fork the `vanus-connect` repo.
1. Create a `sink_google_sheets_proposal.md` based on the `sink_proposal_example.md` under `vanus-connect/proposals` directory. The proposal will introduce how a developer tends to implement the connector in detail. The proposal PR must be approved and merged before going to the next step.
2. Copy one of the sink templates ([Golang template](https://github.com/linkall-labs/vanus-connect/tree/main/templates/sink-go), [Java template](https://github.com/linkall-labs/vanus-connect/tree/main/templates/sink-java)) to `vanus-connect/connectors/` and rename it as `sink-google-sheets`.
3. Implement your connector and submit a PR.
4. Wait the connector to be reviewed and approved.

## How to claim to implement this connector

f you want to solve this issue, please leave a comment in this issue like:

> I'd like to implement the connector, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by ehisakhile** [comment]
Cannot locate the directory called proposals inside vanus-connect.

Cannot find proposal_template.md

**Comment by JieDing** [comment]
> 2\. sink_proposal_example.md

Please check `vanus-connect/proposals/sink_proposal_example.md`

**Comment by ehisakhile** [comment]
I'd like to implement the connector, please assign it to me.

**Comment by ehisakhile** [comment]
I'd like to implement the connector, please assign it to me.

**Comment by JieDing** [comment]
> I'd like to implement the connector, please assign it to me.

Happy you'd like to do this
